### ISSUE TITLE
A couple of errors building with ncurses

### ISSUE THREAD

**Issue by jmaness** [caryman/pong#10]
I encountered an error building with `ncurses` that is described at https://bbs.archlinux.org/viewtopic.php?id=255197 where the `ncursesw/ncurses.h` could not be found. The suggested workaround was to appending the following to `stack.yaml`

```
flags:
  ncurses:
    force-narrow-library: true
```

This helps, but then leads to the following error when building:
```
[1 of 3] Compiling Lib
[2 of 3] Compiling Paths_pong
[3 of 3] Compiling Pong
<command line>: -lpanelw: cannot open shared object file: No such file or directory
```

I'm using Arch linux, so there appears to be some missing system dependencies although from looking at `/usr/lib` I see `ncurses` and `panelw` shared object files.

**Comment by jmaness** [comment]
I had a bit better luck using Ubuntu. I'll create a PR with a Vagrant file that can be used to provision a VM with the required dependencies.

**Comment by jmaness** [comment]
Here's a PR that sets up a dev VM that can build with ncurses: https://github.com/caryman/pong/pull/11

**Comment by caryman** [comment]
I am running a vm with Ubuntu 20.04.3 LTS with no issues. Stack builds pong and runs out of the box.

**Comment by jmaness** [comment]
I'm fine for now using Ubuntu for this project. It looks like the haskell-ncurses project includes `ncursesw/ncurses.h`, but apparenty, it should have included `ncurses.h` instead. Since haskell-ncurses appears to be somewhat abandoned, we'd have to fork that project to fix it, so it's probably not worth that effort. 

For that matter, instead of a VM, I could have probably built a docker container image to reduce resources. Maybe I'll take a look at doing that. I think I will at least upgrade the Vagrant box to Ubuntu 20.04 LTS just so we're all using roughly the same distribution.

**Comment by jmaness** [comment]
I've updated the Ubuntu version to 20.04 LTS in the Vagrantfile in https://github.com/caryman/pong/pull/13. Also, in that PR, I added a Dockerfile with steps to build and run pong within a Docker container which avoids some of the VM overhead. With these multiple options to build and run pong, I'm going to close this issue.
