### ISSUE TITLE
We should get rid of the master branch and prefer main

### ISSUE THREAD

**Issue by dino-** [caryman/pong#9]
The prevailing wisdom is to use `main` as the default branch in git projects instead of `master`. This project has both, with `main` being quite a bit behind `master` (where most of the work is now). We should settle on one of these but doing so requires we coordinate:

- One of us should rebase everything from `master` to `main` and push that
- Everyone else should checkout/switch to main and `pull --set-upstream origin main`
- Everyone should delete their local `master`
- Eventually the "deprecated" `master` branch should be deleted from github's repo

If you want me to do some or all of these steps I can do that, if I have permissions. Also I can elaborate on the git commands needed for these steps if you guys need that.

**Comment by caryman** [comment]
Ok I will try to do this later today and report back.
When I created this project following Git's tutorial, this is what I ended up with. I deleted the project and tried several times to go with either main or master, but always seemed to end up with two branches. Not sure what the procedure is to properly create a project with only main or master (we use master in our stuff).

**Comment by caryman** [comment]
Dino - I will try to give you permissions, if I can work my way thru git's admin pages.

**Comment by jmaness** [comment]
Locally, you can run something like:

```
git fetch origin
git checkout main
get reset --hard origin/master
git push -f
git push --delete origin/master
```

**Comment by jmaness** [comment]
Also, under Settings -> Branches, make sure that `main` is the default branch. If there are any branch protection rules, you might have to temporarily disable/remove them to execute instructions similar to the ones above (e.g. to overwrite the history of the branch.)

**Comment by caryman** [comment]
I ran Jeremy's git commands and deleted master.
Everything should be up to date on main now.
